### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by rahulkathet** [andreekeberg/ml-classify-text-js#9]
Hi,

I was trying to install module on linux server, was able to install the same on mac.

`npm WARN EBADENGINE }
npm ERR! code 127
npm ERR! path /home/www/test/node_modules/core-js-pure
npm ERR! command failed
npm ERR! command sh -c node -e "try{require('./postinstall')}catch(e){}"
npm ERR! sh: node: command not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-04T13_18_28_279Z-debug.log
`

**Comment by andreekeberg** [comment]
Hi @rahulkathet, I'm closing this as it seems your error was related to an issue with your Node installation on the Linux server, and not the package itself.
